const TRANSLATOR = 'TRANSLATOR';
const ACCURACY_REVIEWER = 'ACCURACY_REVIEWER';
const ACCURACY_REFINER = 'ACCURACY_REFINER';
const FLUENCY_REVIEWER = 'FLUENCY_REVIEWER';
const FLUENCY_REFINER = 'FLUENCY_REFINER';
const STYLE_REVIEWER = 'STYLE_REVIEWER';
const STYLE_REFINER = 'STYLE_REFINER';
const CONSISTENCY_REVIEWER = 'CONSISTENCY_REVIEWER';
const CONSISTENCY_REFINER = 'CONSISTENCY_REFINER';
const READABILITY_REVIEWER = 'READABILITY_REVIEWER';
const READABILITY_REFINER = 'READABILITY_REFINER';
const TERMINOLOGY_REVIEWER = 'TERMINOLOGY_REVIEWER';
const TERMINOLOGY_REFINER = 'TERMINOLOGY_REFINER';
const FORMATTING_REVIEWER = 'FORMATTING_REVIEWER';
const FORMATTING_REFINER = 'FORMATTING_REFINER';
const USER_REFINER = 'USER_REFINER';
const SYSTEM_PROMPT = 'SYSTEM_PROMPT';
const USER_PROMPT = 'USER_PROMPT';
const COMBINER = 'COMBINER';

export {
  TRANSLATOR,
  ACCURACY_REVIEWER,
  ACCURACY_REFINER,
  FLUENCY_REVIEWER,
  FLUENCY_REFINER,
  STYLE_REVIEWER,
  STYLE_REFINER,
  CONSISTENCY_REVIEWER,
  CONSISTENCY_REFINER,
  READABILITY_REVIEWER,
  READABILITY_REFINER,
  TERMINOLOGY_REVIEWER,
  TERMINOLOGY_REFINER,
  FORMATTING_REVIEWER,
  FORMATTING_REFINER,
  USER_REFINER,
  COMBINER,
  SYSTEM_PROMPT,
  USER_PROMPT
};